/**
 * Auto-ID Generator
 * Generates unique identifiers using pattern: fileExtension_shortUUID
 * Compatible with existing validation rules (no hyphens)
 */

import * as crypto from 'crypto';

/**
 * Generate a URL-safe short ID (without external dependencies)
 * Uses crypto.randomBytes for secure random generation
 */
function generateShortId(length: number): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    const bytes = crypto.randomBytes(length);
    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars[bytes[i] % chars.length];
    }
    return result;
}

/**
 * Generate a Sylang-compatible ID
 * Pattern: fileExtension_shortUUID
 * Example: req_V1StGXR8Z5jdHi, fun_A2KpMqL9Wx3vN
 */
export function generateSylangId(fileExtension: string): string {
    // Remove leading dot if present
    const ext = fileExtension.replace(/^\./, '');

    // Generate short UUID (14 characters, URL-safe, no hyphens)
    const shortId = generateShortId(14);

    // Combine: ext_shortId
    return `${ext}_${shortId}`;
}

/**
 * Validate if an ID matches the Sylang pattern
 * Used to check if an ID was auto-generated or manually created
 */
export function isAutoGeneratedId(id: string): boolean {
    // Pattern: ext_14characters
    const pattern = /^[a-z]+_[a-zA-Z0-9_-]{14,}$/;
    return pattern.test(id);
}

/**
 * Extract file extension from an auto-generated ID
 * Returns undefined if ID doesn't match pattern
 */
export function extractFileExtensionFromId(id: string): string | undefined {
    const match = id.match(/^([a-z]+)_/);
    return match ? match[1] : undefined;
}
