/**
 * ID Manager - Handles backward compatibility between meaningful IDs and UUIDs
 *
 * Strategy:
 * - Greenfield (new files): Auto-generate UUIDs
 * - Brownfield (existing files): Preserve existing meaningful IDs
 * - New definitions in existing files: Auto-generate UUIDs (unless user specifies)
 */

import { generateSylangId, isAutoGeneratedId } from './autoIdGenerator';

/**
 * Check if an ID is a meaningful ID (user-defined) vs auto-generated UUID
 */
export function isMeaningfulId(id: string): boolean {
    // Meaningful IDs typically:
    // - Don't match UUID pattern (req_14chars)
    // - Have descriptive names like REQ_INPUT_001, EPB_InputProcessingSubsystem_Requirements
    // - May contain underscores, dashes, but are readable

    // Auto-generated pattern: fileExt_14chars (e.g., req_V1StGXR8Z5jd)
    if (isAutoGeneratedId(id)) {
        return false;
    }

    // Meaningful IDs are usually:
    // - Longer than 20 chars (descriptive)
    // - Or follow patterns like REQ_*, EPB_*, etc.
    // - Or are camelCase/PascalCase

    // Simple heuristic: if it doesn't match UUID pattern and is readable, it's meaningful
    return true;
}

/**
 * Preserve existing ID or generate new one
 *
 * @param existingId - ID from parsed DSL (may be null for new definitions)
 * @param fileExtension - File extension for ID generation
 * @returns ID to use (preserved or generated)
 */
export function preserveOrGenerateId(existingId: string | null | undefined, fileExtension: string): string {
    // If ID exists and is meaningful, preserve it
    if (existingId && isMeaningfulId(existingId)) {
        return existingId;
    }

    // If ID exists but is auto-generated (edge case - user might have edited it)
    // Still preserve it to maintain consistency
    if (existingId) {
        return existingId;
    }

    // No existing ID - generate new UUID
    return generateSylangId(fileExtension);
}

/**
 * Validate ID format
 * Checks if ID matches Sylang identifier rules
 */
export function isValidSylangId(id: string): boolean {
    // Sylang IDs must match: /^[a-zA-Z_][a-zA-Z0-9_]*$/
    return /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(id);
}

/**
 * Check if ID change would break references
 * (To be integrated with Symbol Manager)
 */
export function wouldBreakReferences(oldId: string, newId: string): boolean {
    // TODO: Integrate with Symbol Manager to check:
    // - Are there other files referencing oldId?
    // - Would newId conflict with existing IDs?
    // - Are there traceability links using oldId?

    // For now, return false (assume safe)
    // This will be enhanced with Symbol Manager integration
    return false;
}

/**
 * Get ID display name
 * For UI display - shows meaningful IDs as-is, UUIDs can be truncated
 */
export function getDisplayId(id: string, maxLength: number = 30): string {
    if (isMeaningfulId(id)) {
        return id; // Show full meaningful ID
    }

    // For UUIDs, optionally truncate for display
    if (id.length > maxLength) {
        return id.substring(0, maxLength) + '...';
    }

    return id;
}

/**
 * Extract ID from definition line
 * Handles both formats:
 * - def requirement REQ_INPUT_001
 * - def requirement req_V1StGXR8Z5jd
 */
export function extractIdFromDefLine(tokens: string[]): string | null {
    if (tokens.length < 3) {
        return null;
    }

    // Format: def keyword identifier
    const id = tokens[2];
    return id || null;
}
